In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image
import seaborn as sns
import datetime

%matplotlib inline

In [3]:
import pandas as pd

turnstiles = pd.read_pickle('final_turnstile_data.pkl')

In [4]:
turnstiles.head()

,c/a,unit,scp,station,linename,division,date,time,desc,entries,...,datetime,datetime_clean,entries_diff,exit_diff,year,group_id,group_id_clean,grou_id_num,group_id_num,first_row_group
29652,H007,R248,00-00-00,1 AV,L,BMT,03/26/2016,00:00:00,REGULAR,10883649,...,03/26/2016 00:00:00,2016-03-26 00:00:00,NaN,NaN,2016,H007R24800-00-001 AV2016,H007R24800-00-001 AV2016,6223,6223,True
29653,H007,R248,00-00-00,1 AV,L,BMT,03/26/2016,04:00:00,REGULAR,10883779,...,03/26/2016 04:00:00,2016-03-26 04:00:00,130.0,371.0,2016,H007R24800-00-001 AV2016,H007R24800-00-001 AV2016,6223,6223,False
29654,H007,R248,00-00-00,1 AV,L,BMT,03/26/2016,08:00:00,REGULAR,10883856,...,03/26/2016 08:00:00,2016-03-26 08:00:00,77.0,266.0,2016,H007R24800-00-001 AV2016,H007R24800-00-001 AV2016,6223,6223,False
29655,H007,R248,00-00-00,1 AV,L,BMT,03/26/2016,12:00:00,REGULAR,10884397,...,03/26/2016 12:00:00,2016-03-26 12:00:00,541.0,712.0,2016,H007R24800-00-001 AV2016,H007R24800-00-001 AV2016,6223,6223,False
29656,H007,R248,00-00-00,1 AV,L,BMT,03/26/2016,16:00:00,REGULAR,10885131,...,03/26/2016 16:00:00,2016-03-26 16:00:00,734.0,1147.0,2016,H007R24800-00-001 AV2016,H007R24800-00-001 AV2016,6223,6223,False

In [5]:
turnstiles.head()
turnstiles.describe()

,entries,exits,entries_diff,exit_diff,year,grou_id_num,group_id_num
count,5.481151e+06,5.481151e+06,5.471787e+06,5.471787e+06,5.481151e+06,5.481151e+06,5.481151e+06
mean,3.668874e+07,2.942573e+07,4.164207e+03,2.215778e+03,2.016504e+03,4.683237e+03,4.683237e+03
std,1.995975e+08,1.789708e+08,3.712479e+06,3.654597e+06,4.999825e-01,2.704192e+03,2.704192e+03
min,0.000000e+00,0.000000e+00,-2.130766e+09,-2.097170e+09,2.016000e+03,0.000000e+00,0.000000e+00
25%,5.403665e+05,2.665350e+05,1.000000e+01,8.000000e+00,2.016000e+03,2.343000e+03,2.343000e+03
50%,2.597810e+06,1.490638e+06,7.900000e+01,5.300000e+01,2.017000e+03,4.681000e+03,4.681000e+03
75%,6.628317e+06,4.688856e+06,2.540000e+02,1.700000e+02,2.017000e+03,7.027000e+03,7.027000e+03
max,2.147483e+09,2.097170e+09,2.076115e+09,2.038812e+09,2.017000e+03,9.363000e+03,9.363000e+03

In [6]:
turnstiles.loc[turnstiles['entries_diff'] < 0, 'entries_diff'] = None
turnstiles.loc[turnstiles['exit_diff'] < 0, 'exit_diff'] = None

In [7]:
turnstiles['day'] = [datetime.datetime.strftime(x, '%Y-%m-%d') for x in turnstiles['datetime_clean']]
turnstiles['all_traffic'] = turnstiles['entries_diff'] + turnstiles['exit_diff']

In [9]:
turnstiles.head()

,c/a,unit,scp,station,linename,division,date,time,desc,entries,...,entries_diff,exit_diff,year,group_id,group_id_clean,grou_id_num,group_id_num,first_row_group,day,all_traffic
29652,H007,R248,00-00-00,1 AV,L,BMT,03/26/2016,00:00:00,REGULAR,10883649,...,NaN,NaN,2016,H007R24800-00-001 AV2016,H007R24800-00-001 AV2016,6223,6223,True,2016-03-26,NaN
29653,H007,R248,00-00-00,1 AV,L,BMT,03/26/2016,04:00:00,REGULAR,10883779,...,130.0,371.0,2016,H007R24800-00-001 AV2016,H007R24800-00-001 AV2016,6223,6223,False,2016-03-26,501.0
29654,H007,R248,00-00-00,1 AV,L,BMT,03/26/2016,08:00:00,REGULAR,10883856,...,77.0,266.0,2016,H007R24800-00-001 AV2016,H007R24800-00-001 AV2016,6223,6223,False,2016-03-26,343.0
29655,H007,R248,00-00-00,1 AV,L,BMT,03/26/2016,12:00:00,REGULAR,10884397,...,541.0,712.0,2016,H007R24800-00-001 AV2016,H007R24800-00-001 AV2016,6223,6223,False,2016-03-26,1253.0
29656,H007,R248,00-00-00,1 AV,L,BMT,03/26/2016,16:00:00,REGULAR,10885131,...,734.0,1147.0,2016,H007R24800-00-001 AV2016,H007R24800-00-001 AV2016,6223,6223,False,2016-03-26,1881.0

In [10]:
# See if there are multiple stations per line or division
turnstiles.groupby(['station', 'linename', 'division']).sum()

                                             entries          exits  \
station         linename     division
1 AV            L            BMT       1857746413372  2581828352367
103 ST          1            IRT         71894962569    37821143560
                6            IRT         72262955551   638275545164
                BC           IND         30707992921    27268335397
103 ST-CORONA   7            IRT         79592792001    75105466573
104 ST          A            IND       2065169547107  2071661647383
                JZ           BMT       3027326515084  1895569097611
110 ST          6            IRT         34446293911    34806267216
111 ST          7            IRT         50598679607    30523126408
                A            IND         78790482636    29075010670
                J            BMT         18640604925    16985384000
116 ST          23           IRT         37983633928    18203571054
                6            IRT         46134256734    38671332290
                BC           IND       1948056867069  2401822531398
116 ST-COLUMBIA 1            IRT       1441593596069   306318396350
121 ST          JZ           BMT         17750393184     7516299600
125 ST          1            IRT        735621399282   380292471242
                23           IRT       4240677541015  2632627047796
                456          IRT       2445389333170  1051104629310
                ACBD         IND        576818260994   479551714888
135 ST          23           IRT         46880655741    19151014249
                BC           IND        239405980312    36596656057
137 ST CITY COL 1            IRT        531236145844  1055050484166
138/GRAND CONC  45           IRT       1175500060370  1135114868067
14 ST           123FLM       IRT       1779249110834  1891338438832
                ACEL         IND       1571317087741   740752137514
                FLM123       IND         70865330561    75310404856
14 ST-UNION SQ  456LNQR      IRT        190146331938    49524375729
                456LNQRW     IRT        178849513896    51169458385
                LNQR456      BMT        679929898095   256356849728
...                                              ...            ...
TIMES SQ-42 ST  ACENQRS1237  BMT          7342029657    11079582209
                ACENQRS1237W BMT          9703372194    14601244281
TOMPKINSVILLE   1            SRT         10832279172     2951064394
TREMONT AV      BD           IND        161004250856    14949650040
TWENTY THIRD ST 1            PTH          4120821339     2537672189
UNION ST        R            BMT         25598038641    26457889567
UTICA AV        AC           IND        172264664371    62087642111
V.CORTLANDT PK  1            IRT         23337685625     8997423884
VAN SICLEN AV   3            IRT         18263991448    10969042028
                JZ           BMT         15323768612    15023642967
VAN SICLEN AVE  C            IND         14841337640    15333054203
VERNON-JACKSON  7            IRT         42089450432    28699960856
W 4 ST-WASH SQ  ABCDEFM      IND        733322284978   617616329250
W 8 ST-AQUARIUM FQ           BMT         13472840574    14576977744
WAKEFIELD/241   2            IRT         20563154359    21249530111
WALL ST         23           IRT        135243732216   119033911983
                45           IRT        635816328909   333767999969
WEST FARMS SQ   25           IRT        520891101118    85394346893
WESTCHESTER SQ  6            IRT         29229776942    27065113113
WHITEHALL S-FRY R1           BMT        159388634755    37610496084
                R1W          BMT        160044827681    39744167485
WHITLOCK AV     6            IRT        263497798047    25050135555
WILSON AV       L            BMT         14226245085    12774642690
WINTHROP ST     25           IRT         33273295461     6490547239
WOODHAVEN BLVD  JZ           BMT        135479065087    71455072957
                MR           IND         61269159508    42344873813
WOODLAWN        4            IRT         34363720902    13776465223
WORLD TRADE CTR ACE23        IND         43785281894    22163021942
YORK ST         F            IND         39982187002    35725609688
ZEREGA AV       6            IRT         63020095965     1191251488

                                       entries_diff     exit_diff      year  \
station         linename     division
1 AV            L            BMT       1.625140e+09  1.710573e+08  23911621
103 ST          1            IRT       2.360185e+06  1.104824e+06  14151832
                6            IRT       2.259567e+06  1.720895e+06  14327316
                BC           IND       8.291280e+05  6.030100e+05   7144464
103 ST-CORONA   7            IRT       3.574584e+06  2.633143e+06  21659180
104 ST          A            IND       2.806780e+05  1.075900e+05  11867089
                JZ           BMT       1.119424e+09  1.906422e+09   9259702
110 ST          6            IRT       2.275721e+06  1.771148e+06  14500629
111 ST          7            IRT       2.078639e+06  1.365091e+06  11893320
                A            IND       1.663685e+08  3.365167e+07  16684496
                J            BMT       4.957360e+05  2.888470e+05   9556195
116 ST          23           IRT       2.179875e+06  9.462650e+05  19118441
                6            IRT       2.906565e+06  1.551406e+06  19178902
                BC           IND       1.260165e+06  6.386960e+05  14355450
116 ST-COLUMBIA 1            IRT       2.507427e+06  1.289969e+06  14375590
121 ST          JZ           BMT       2.924550e+05  1.312760e+05  10858552
125 ST          1            IRT       6.363912e+08  3.188989e+08  11988085
                23           IRT       1.939060e+09  1.488382e+09  18981339
                456          IRT       4.460949e+06  4.338710e+06  33774373
                ACBD         IND       5.309198e+06  4.230103e+06  38357823
135 ST          23           IRT       2.739223e+06  8.213860e+05  28622222
                BC           IND       9.622880e+05  7.234250e+05  26077359
137 ST CITY COL 1            IRT       2.537478e+06  1.961092e+06  23786629
138/GRAND CONC  45           IRT       5.876250e+05  5.088070e+05   7142440
14 ST           123FLM       IRT       4.103852e+06  2.288139e+06  35702015
                ACEL         IND       3.340128e+06  2.867482e+06  23806814
                FLM123       IND       3.184024e+06  3.621315e+06  42661038
14 ST-UNION SQ  456LNQR      IRT       3.073653e+06  2.697544e+06  15363936
                456LNQRW     IRT       2.897402e+06  2.333253e+06  14151272
                LNQR456      BMT       6.437669e+06  5.459444e+06  31860864
...                                             ...           ...       ...
TIMES SQ-42 ST  ACENQRS1237  BMT       1.014991e+06  1.549190e+06   9594144
                ACENQRS1237W BMT       1.216568e+06  1.784107e+06   9596886
TOMPKINSVILLE   1            SRT       4.060470e+05  6.553700e+04  16849813
TREMONT AV      BD           IND       1.773796e+06  1.082320e+06  22320559
TWENTY THIRD ST 1            PTH       3.230831e+06  2.755175e+06  20088384
UNION ST        R            BMT       1.079023e+06  8.686680e+05  14407881
UTICA AV        AC           IND       2.910013e+06  2.182370e+06  31058186
V.CORTLANDT PK  1            IRT       1.256396e+06  5.380840e+05   9592491
VAN SICLEN AV   3            IRT       7.101530e+05  7.271130e+05   9497746
                JZ           BMT       5.266900e+05  5.221970e+05   7130343
VAN SICLEN AVE  C            IND       5.770340e+05  5.218500e+05   7059744
VERNON-JACKSON  7            IRT       2.719304e+06  1.989126e+06  30842370
W 4 ST-WASH SQ  ABCDEFM      IND       1.253382e+08  7.354682e+06  45330897
W 8 ST-AQUARIUM FQ           BMT       4.676500e+05  3.741590e+05  19007535
WAKEFIELD/241   2            IRT       9.521820e+05  9.757090e+05  11854999
WALL ST         23           IRT       4.323396e+06  4.161921e+06  52626577
                45           IRT       2.133544e+09  1.360067e+09  66820683
WEST FARMS SQ   25           IRT       1.379215e+06  8.829050e+05  21524104
WESTCHESTER SQ  6            IRT       1.068301e+06  9.488380e+05   7146477
WHITEHALL S-FRY R1           BMT       1.506747e+06  1.417884e+06  18200448
                R1W          BMT       2.283261e+06  1.602953e+06  17888773
WHITLOCK AV     6            IRT       3.274290e+05  3.347530e+05  14327216
WILSON AV       L            BMT       5.949600e+05  5.391110e+05   8625292
WINTHROP ST     25           IRT       1.194679e+06  2.531520e+05   9606587
WOODHAVEN BLVD  JZ           BMT       1.686123e+08  5.069788e+07  18981327
                MR           IND       3.861050e+06  2.231996e+06  26414114
WOODLAWN        4            IRT       1.305406e+06  3.090030e+05  11921556
WORLD TRADE CTR ACE23        IND       3.744247e+06  1.533246e+06  26032993
YORK ST         F            IND       1.858096e+06  1.085177e+06   7108155
ZEREGA AV       6            IRT       4.388650e+05  4.020950e+05  14079202

                                       grou_id_num  group_id_num  \
station         linename     division
1 AV            L            BMT          66842589      66842589
103 ST          1            IRT          30196732      30196732
                6            IRT          27307452      27307452
                BC           IND          15158101      15158101
103 ST-CORONA   7            IRT          56976735      56976735
104 ST          A            IND          32447770      32447770
                JZ           BMT          24693821      24693821
110 ST          6            IRT          31378449      31378449
111 ST          7            IRT          37039481      37039481
                A            IND          42369640      42369640
                J            BMT          29151647      29151647
116 ST          23           IRT          45357128      45357128
                6            IRT          48062242      48062242
                BC           IND          35281711      35281711
116 ST-COLUMBIA 1            IRT          31372586      31372586
121 ST          JZ           BMT          23196304      23196304
125 ST          1            IRT          28626938      28626938
                23           IRT          41273844      41273844
                456          IRT          67567549      67567549
                ACBD         IND          94182684      94182684
135 ST          23           IRT          71682961      71682961
                BC           IND          58442626      58442626
137 ST CITY COL 1            IRT          49713241      49713241
138/GRAND CONC  45           IRT          26285063      26285063
14 ST           123FLM       IRT          81445692      81445692
                ACEL         IND          57705002      57705002
                FLM123       IND         101316248     101316248
14 ST-UNION SQ  456LNQR      IRT          37941899      37941899
                456LNQRW     IRT          38524914      38524914
                LNQR456      BMT          69882212      69882212
...                                            ...           ...
TIMES SQ-42 ST  ACENQRS1237  BMT          21174165      21174165
                ACENQRS1237W BMT          15064469      15064469
TOMPKINSVILLE   1            SRT          45797981      45797981
TREMONT AV      BD           IND          45074617      45074617
TWENTY THIRD ST 1            PTH          50787724      50787724
UNION ST        R            BMT          28652074      28652074
UTICA AV        AC           IND          70842793      70842793
V.CORTLANDT PK  1            IRT          20670981      20670981
VAN SICLEN AV   3            IRT          24754168      24754168
                JZ           BMT          13061711      13061711
VAN SICLEN AVE  C            IND          16447781      16447781
VERNON-JACKSON  7            IRT          71576924      71576924
W 4 ST-WASH SQ  ABCDEFM      IND         104450015     104450015
W 8 ST-AQUARIUM FQ           BMT          48373091      48373091
WAKEFIELD/241   2            IRT          31037868      31037868
WALL ST         23           IRT         122639973     122639973
                45           IRT         142879389     142879389
WEST FARMS SQ   25           IRT          47335239      47335239
WESTCHESTER SQ  6            IRT          17947903      17947903
WHITEHALL S-FRY R1           BMT          38308765      38308765
                R1W          BMT          46205423      46205423
WHITLOCK AV     6            IRT          45771428      45771428
WILSON AV       L            BMT          18617177      18617177
WINTHROP ST     25           IRT          24784889      24784889
WOODHAVEN BLVD  JZ           BMT          42285036      42285036
                MR           IND          49019146      49019146
WOODLAWN        4            IRT          32129855      32129855
WORLD TRADE CTR ACE23        IND          59223395      59223395
YORK ST         F            IND          17529780      17529780
ZEREGA AV       6            IRT          31515655      31515655

                                       first_row_group   all_traffic
station         linename     division
1 AV            L            BMT                  20.0  1.796177e+09
103 ST          1            IRT                  12.0  3.465009e+06
                6            IRT                  15.0  3.980462e+06
                BC           IND                   6.0  1.432138e+06
103 ST-CORONA   7            IRT                  18.0  6.207727e+06
104 ST          A            IND                  10.0  3.832570e+05
                JZ           BMT                   8.0  3.025821e+09
110 ST          6            IRT                  12.0  4.046869e+06
111 ST          7            IRT                  10.0  3.443730e+06
                A            IND                  14.0  1.175264e+08
                J            BMT                   8.0  7.845830e+05
116 ST          23           IRT                  16.0  3.126140e+06
                6            IRT                  16.0  4.457971e+06
                BC           IND                  12.0  1.691064e+06
116 ST-COLUMBIA 1            IRT                  12.0  3.797396e+06
121 ST          JZ           BMT                  10.0  4.237310e+05
125 ST          1            IRT                  10.0  9.552902e+08
                23           IRT                  16.0  3.427139e+09
                456          IRT                  28.0  8.532191e+06
                ACBD         IND                  32.0  9.539301e+06
135 ST          23           IRT                  24.0  3.560609e+06
                BC           IND                  22.0  1.685713e+06
137 ST CITY COL 1            IRT                  20.0  4.444762e+06
138/GRAND CONC  45           IRT                   6.0  1.096432e+06
14 ST           123FLM       IRT                  30.0  6.391991e+06
                ACEL         IND                  20.0  6.207610e+06
                FLM123       IND                  36.0  6.805339e+06
14 ST-UNION SQ  456LNQR      IRT                  12.0  5.771197e+06
                456LNQRW     IRT                  12.0  5.230655e+06
                LNQR456      BMT                  26.0  1.189711e+07
...                                                ...           ...
TIMES SQ-42 ST  ACENQRS1237  BMT                   8.0  2.564181e+06
                ACENQRS1237W BMT                   8.0  3.000675e+06
TOMPKINSVILLE   1            SRT                  14.0  4.715840e+05
TREMONT AV      BD           IND                  18.0  2.856116e+06
TWENTY THIRD ST 1            PTH                  18.0  5.986006e+06
UNION ST        R            BMT                  12.0  1.947691e+06
UTICA AV        AC           IND                  26.0  5.092383e+06
V.CORTLANDT PK  1            IRT                   8.0  1.794480e+06
VAN SICLEN AV   3            IRT                   9.0  1.437266e+06
                JZ           BMT                   6.0  1.048887e+06
VAN SICLEN AVE  C            IND                   6.0  1.098884e+06
VERNON-JACKSON  7            IRT                  26.0  4.708430e+06
W 4 ST-WASH SQ  ABCDEFM      IND                  38.0  1.326929e+08
W 8 ST-AQUARIUM FQ           BMT                  16.0  8.418090e+05
WAKEFIELD/241   2            IRT                  10.0  1.927891e+06
WALL ST         23           IRT                  44.0  8.485317e+06
                45           IRT                  56.0  3.493611e+09
WEST FARMS SQ   25           IRT                  18.0  2.262120e+06
WESTCHESTER SQ  6            IRT                   6.0  2.017139e+06
WHITEHALL S-FRY R1           BMT                  15.0  2.924631e+06
                R1W          BMT                  15.0  3.254298e+06
WHITLOCK AV     6            IRT                  12.0  6.621820e+05
WILSON AV       L            BMT                  11.0  1.134071e+06
WINTHROP ST     25           IRT                   8.0  1.447831e+06
WOODHAVEN BLVD  JZ           BMT                  16.0  1.206348e+06
                MR           IND                  22.0  6.093046e+06
WOODLAWN        4            IRT                  10.0  1.614409e+06
WORLD TRADE CTR ACE23        IND                  22.0  5.277493e+06
YORK ST         F            IND                   6.0  2.943273e+06
ZEREGA AV       6            IRT                  12.0  8.409600e+05

[516 rows x 9 columns]

In [41]:
stations_day = turnstiles.groupby(['station', 'day']).sum()
stations_day.reset_index(inplace=True)

In [42]:
stations_day.head()

,station,day,entries,exits,entries_diff,exit_diff,year,grou_id_num,group_id_num,first_row_group,all_traffic
0,1 AV,2016-03-26,9360477057,20851658620,14546.0,12567.0,120960,350202,350202,10.0,26946.0
1,1 AV,2016-03-27,9360582797,20851729162,15446.0,13530.0,120960,350202,350202,0.0,28768.0
2,1 AV,2016-03-28,9360681182,20851799152,22046.0,18583.0,120960,350202,350202,0.0,40406.0
3,1 AV,2016-03-29,9360821714,20851885465,24190.0,19799.0,120960,350202,350202,0.0,43708.0
4,1 AV,2016-03-30,9360969635,20851976717,24818.0,20575.0,120960,350202,350202,0.0,45065.0

In [1]:
daily_mean = stations_day.groupby('station')['all_traffic'].mean()
daily_mean.head()

NameError: name 'stations_day' is not defined