# Finding Station Locations

## Import the libraries

In [14]:
import pandas as pd
import numpy as np
import sys

print("Python Version:", sys.version)
print("Pandas Version:", pd.__version__)
print("Numpy Version:", np.__version__)

Python Version: 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Pandas Version: 0.20.3
Numpy Version: 1.13.3

## Read in the data
### Read in station location data
We pulled station location data from the MTA website

In [5]:
stations = pd.read_csv('http://web.mta.info/developers/data/nyct/subway/Stations.csv')
stations.head()

,Station ID,Complex ID,GTFS Stop ID,Division,Line,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude
0,1,1,R01,BMT,Astoria,Astoria - Ditmars Blvd,Q,N W,Elevated,40.775036,-73.912034
1,2,2,R03,BMT,Astoria,Astoria Blvd,Q,N W,Elevated,40.770258,-73.917843
2,3,3,R04,BMT,Astoria,30 Av,Q,N W,Elevated,40.766779,-73.921479
3,4,4,R05,BMT,Astoria,Broadway,Q,N W,Elevated,40.761820,-73.925508
4,5,5,R06,BMT,Astoria,36 Av,Q,N W,Elevated,40.756804,-73.929575

### Read in our cleaned turnstile data

In [6]:
turns = pd.read_pickle('data/cleaned_turnstile_data.pkl')
turns.head()

,c/a,unit,scp,station,linename,division,date,time,desc,entries,...,group_id,station_id,entries_diff,exit_diff,first_row_group,entries_outlier,exit_outlier,all_traffic,week,hour
196410,R730,R431,00-00-01,EASTCHSTER/DYRE,5,IRT,03/25/2017,05:00:00,REGULAR,5899854,...,0,EASTCHSTER/DYRE5IRT,1.0,5.0,False,False,False,6.0,12,5
196411,R730,R431,00-00-01,EASTCHSTER/DYRE,5,IRT,03/25/2017,09:00:00,REGULAR,5899857,...,0,EASTCHSTER/DYRE5IRT,3.0,5.0,False,False,False,8.0,12,9
196412,R730,R431,00-00-01,EASTCHSTER/DYRE,5,IRT,03/25/2017,13:00:00,REGULAR,5899857,...,0,EASTCHSTER/DYRE5IRT,0.0,1.0,False,False,False,1.0,12,13
196413,R730,R431,00-00-01,EASTCHSTER/DYRE,5,IRT,03/25/2017,17:00:00,REGULAR,5899857,...,0,EASTCHSTER/DYRE5IRT,0.0,4.0,False,False,False,4.0,12,17
196414,R730,R431,00-00-01,EASTCHSTER/DYRE,5,IRT,03/25/2017,21:00:00,REGULAR,5899857,...,0,EASTCHSTER/DYRE5IRT,0.0,2.0,False,False,False,2.0,12,21

### Read in a join table

As you might have noticed, there is not common field to merge the stations data with our turnstile data :( But don't worry!! We found a super handy table that links the station ID from the stations table to a booth id which corresponds to the control area id (c/a) in our turnstile data (Yay!!!) 

Let's read in that join table

*File downloaded from: https://docs.google.com/spreadsheets/d/10sz0xWODQ02Kemx6ovS0NLQ_gA0YV9YQtdD7uiCcyjI/edit?usp=sharing&authkey=CMTzrvwE*

In [7]:
join_table = pd.read_csv('data/Remote-Booth-Station - turnstiles 2013.csv')
join_table.head()

  Remote Booth stop_id.2013   Station.2013 Line.2013 Division.2013
0   R051  A002          R11  LEXINGTON AVE    456NQR           BMT
1   R050  A004          R11  LEXINGTON AVE    456NQR           BMT
2   R079  A006          R13    5 AVE-59 ST       NQR           BMT
3   R079  A007          R13    5 AVE-59 ST       NQR           BMT
4   R080  A010          R14    57 ST-7 AVE       NQR           BMT

## Join the turnstile data with station locations

### Join the stations data with our join file to get booth id

In [8]:
stations_booth = pd.merge(join_table ,stations,how='left',left_on='stop_id.2013',right_on='GTFS Stop ID')
stations_booth.head()

,Remote,Booth,stop_id.2013,Station.2013,Line.2013,Division.2013,Station ID,Complex ID,GTFS Stop ID,Division,Line,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude
0,R051,A002,R11,LEXINGTON AVE,456NQR,BMT,7.0,613.0,R11,BMT,Astoria,Lexington Av/59 St,M,N W R,Subway,40.762660,-73.967258
1,R050,A004,R11,LEXINGTON AVE,456NQR,BMT,7.0,613.0,R11,BMT,Astoria,Lexington Av/59 St,M,N W R,Subway,40.762660,-73.967258
2,R079,A006,R13,5 AVE-59 ST,NQR,BMT,8.0,8.0,R13,BMT,Astoria,5 Av/59 St,M,N W R,Subway,40.764811,-73.973347
3,R079,A007,R13,5 AVE-59 ST,NQR,BMT,8.0,8.0,R13,BMT,Astoria,5 Av/59 St,M,N W R,Subway,40.764811,-73.973347
4,R080,A010,R14,57 ST-7 AVE,NQR,BMT,9.0,9.0,R14,BMT,Broadway - Brighton,57 St - 7 Av,M,N Q R W,Subway,40.764664,-73.980658

In [9]:
missing = stations_booth['GTFS Latitude'].isnull().sum()

print("We're missing the stop id in our join table for {} stations".format(missing))
print("...but we have booth data for {} of our total stations!".format(round((len(stations_booth)-missing)/len(stations_booth),2)))

We're missing the stop id in our join table for 41 stations
...but we have booth data for 0.95 of our total stations!

### Join the turnstile data with our stations data

In [10]:
turns_loc = pd.merge(turns, stations_booth, how='inner',left_on='c/a',right_on='Booth')
turns_loc.head()

,c/a,unit,scp,station,linename,division,date,time,desc,entries,...,Complex ID,GTFS Stop ID,Division,Line,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude
0,R730,R431,00-00-01,EASTCHSTER/DYRE,5,IRT,03/25/2017,05:00:00,REGULAR,5899854,...,442.0,501,IRT,Dyre Av,Eastchester - Dyre Av,Bx,5,At Grade,40.8883,-73.830834
1,R730,R431,00-00-01,EASTCHSTER/DYRE,5,IRT,03/25/2017,09:00:00,REGULAR,5899857,...,442.0,501,IRT,Dyre Av,Eastchester - Dyre Av,Bx,5,At Grade,40.8883,-73.830834
2,R730,R431,00-00-01,EASTCHSTER/DYRE,5,IRT,03/25/2017,13:00:00,REGULAR,5899857,...,442.0,501,IRT,Dyre Av,Eastchester - Dyre Av,Bx,5,At Grade,40.8883,-73.830834
3,R730,R431,00-00-01,EASTCHSTER/DYRE,5,IRT,03/25/2017,17:00:00,REGULAR,5899857,...,442.0,501,IRT,Dyre Av,Eastchester - Dyre Av,Bx,5,At Grade,40.8883,-73.830834
4,R730,R431,00-00-01,EASTCHSTER/DYRE,5,IRT,03/25/2017,21:00:00,REGULAR,5899857,...,442.0,501,IRT,Dyre Av,Eastchester - Dyre Av,Bx,5,At Grade,40.8883,-73.830834

In [11]:
missing_t = turns_loc['GTFS Latitude'].isnull().sum()

print("We're missing the corresponding c/a id for {} turnstile records".format(missing_t))
print("...but we have location data for {} of our total turnstile records!".format(round((len(turns_loc)-missing_t)/len(turns_loc),2)))

We're missing the corresponding c/a id for 362630 turnstile records
...but we have location data for 0.93 of our total turnstile records!

Check out the station names from the turnstile data and station loc data to make sure they agree

In [12]:
diff_stations = [(x, y) for x, y in zip(turns_loc['station'], turns_loc['Stop Name'])]
set(diff_stations)

{('PELHAM BAY PARK', 'Pelham Bay Park'),
 ('QUEENS PLAZA', 'Queens Plaza'),
 ('ROOSEVELT ISLND', 'Roosevelt Island'),
 ("B'WAY-LAFAYETTE", 'Broadway-Lafayette St'),
 ('EAST 105 ST', 'E 105 St'),
 ('61 ST WOODSIDE', 'Woodside - 61 St'),
 ('WHITLOCK AV', 'Whitlock Av'),
 ('NECK RD', 'Neck Rd'),
 ('GRAND ARMY PLAZ', 'Grand Army Plaza'),
 ('81 ST-MUSEUM', '81 St - Museum of Natural History'),
 ('NOSTRAND AV', 'Nostrand Av'),
 ('CYPRESS AV', 'Cypress Av'),
 ('NASSAU ST', 'Nassau Av'),
 ('SUTTER AV', 'Sutter Av'),
 ('KINGS HWY', 'Kings Hwy'),
 ('225 ST', '225 St'),
 ('HEWES ST', 'Hewes St'),
 ('FLATBUSH AV-B.C', 'Flatbush Av - Brooklyn College'),
 ('JKSN HT-ROOSVLT', 'Jackson Hts - Roosevelt Av'),
 ('LAFAYETTE AV', 'Lafayette Av'),
 ('167 ST', '167 St'),
 ('BROADWAY JCT', 'Broadway Jct'),
 ('GRAND-NEWTOWN', 'Grand Av - Newtown'),
 ('67 AV', '67 Av'),
 ('137 ST CITY COL', '137 St - City College'),
 ('EUCLID AV', 'Euclid Av'),
 ('57 ST', '57 St'),
 ('59 ST', 'Lexington Av/59 St'),
 ('BEACH 25 ST', 'Beach 25 St'),
 ('FRANKLIN ST', 'Franklin St'),
 ('VERNON-JACKSON', 'Vernon Blvd - Jackson Av'),
 ('HOWARD BCH JFK', 'Howard Beach - JFK Airport'),
 ('7 AV', '7 Av'),
 ('SUTTER AV-RUTLD', 'Sutter Av - Rutland Rd'),
 ('36 AV', '36 Av'),
 ('LEXINGTON AV/63', 'Lexington Av/63 St'),
 ('JAMAICA 179 ST', 'Jamaica - 179 St'),
 ('4AV-9 ST', '9 St'),
 ('MARBLE HILL-225', 'Marble Hill - 225 St'),
 ('BUSHWICK AV', 'Bushwick Av - Aberdeen St'),
 ('59 ST', '59 St'),
 ('34 ST-HERALD SQ', '34 St - Herald Sq'),
 ('BROAD ST', 'Broad St'),
 ('WESTCHESTER SQ', 'Westchester Sq - E Tremont Av'),
 ('MORGAN AV', 'Morgan Av'),
 ('CHAUNCEY ST', 'Chauncey St'),
 ('155 ST', '155 St'),
 ('KEW GARDENS', 'Kew Gardens - Union Tpke'),
 ('CRESCENT ST', 'Crescent St'),
 ('CLINTON-WASH AV', 'Clinton - Washington Avs'),
 ('77 ST', '77 St'),
 ('BURNSIDE AV', 'Burnside Av'),
 ('53 ST', '53 St'),
 ('EASTN PKWY-MUSM', 'Eastern Pkwy - Brooklyn Museum'),
 ('145 ST', nan),
 ('COURT SQ-23 ST', 'Court Sq'),
 ('BEACH 98 ST', nan),
 ('FT HAMILTON PKY', 'Fort Hamilton Pkwy'),
 ('68ST-HUNTER CO', '68 St - Hunter College'),
 ('5 AV/53 ST', '5 Av/53 St'),
 ('THIRTY ST', nan),
 ('CHURCH AV', 'Church Av'),
 ('JUNIUS ST', 'Junius St'),
 ('EASTCHSTER/DYRE', 'Eastchester - Dyre Av'),
 ('WAKEFIELD/241', 'Wakefield - 241 St'),
 ('BEDFORD-NOSTRAN', 'Bedford - Nostrand Avs'),
 ('GRAHAM AV', 'Graham Av'),
 ('JOURNAL SQUARE', nan),
 ('FLUSHING-MAIN', 'Flushing - Main St'),
 ('ORCHARD BEACH', nan),
 ('CYPRESS HILLS', 'Cypress Hills'),
 ('AVENUE N', 'Avenue N'),
 ('HOYT ST', 'Hoyt St'),
 ('NEWARK C', nan),
 ('168 ST', '168 St - Washington Hts'),
 ('74 ST-BROADWAY', '74 St - Broadway'),
 ('40 ST LOWERY ST', '40 St'),
 ('125 ST', '125 St'),
 ('46 ST', '46 St'),
 ('WINTHROP ST', 'Winthrop St'),
 ('33 ST', '33 St'),
 ('JAMAICA VAN WK', 'Jamaica - Van Wyck'),
 ('85 ST-FOREST PK', '85 St - Forest Pkwy'),
 ('CANARSIE-ROCKAW', 'Canarsie - Rockaway Pkwy'),
 ('HOYT-SCHER', 'Hoyt - Schermerhorn Sts'),
 ('BEACH 105 ST', nan),
 ('BEDFORD PK BLVD', 'Bedford Park Blvd - Lehman College'),
 ('SHEEPSHEAD BAY', 'Sheepshead Bay'),
 ('EAST BROADWAY', 'East Broadway'),
 ('ELMHURST AV', 'Elmhurst Av'),
 ('BRIGHTON BEACH', 'Brighton Beach'),
 ('ST LAWRENCE AV', 'St Lawrence Av'),
 ('65 ST', '65 St'),
 ('NASSAU AV', 'Nassau Av'),
 ('CHRISTOPHER ST', 'Christopher St - Sheridan Sq'),
 ('47-50 STS ROCK', '47-50 Sts - Rockefeller Ctr'),
 ('18 ST', '18 St'),
 ('LACKAWANNA', nan),
 ('46 ST BLISS ST', '46 St'),
 ('3 AV-149 ST', '3 Av - 149 St'),
 ('PENNSYLVANIA AV', 'Pennsylvania Av'),
 ('NEREID AV', 'Nereid Av'),
 ('BEACH 90 ST', 'Beach 90 St'),
 ('55 ST', '55 St'),
 ('KINGSBRIDGE RD', 'Kingsbridge Rd'),
 ('FRANKLIN AV', 'Franklin Av'),
 ('WALL ST', 'Wall St'),
 ('STERLING ST', 'Sterling St'),
 ('KINGSTON-THROOP', 'Kingston - Throop Avs'),
 ('66 ST-LINCOLN', '66 St - Lincoln Center'),
 ('PROSPECT PARK', 'Prospect Park'),
 ('TIMES SQ-42 ST', 'Times Sq - 42 St'),
 ('UTICA AV', 'Utica Av'),
 ('86 ST', '86 St'),
 ('BEACH 67 ST', 'Beach 67 St'),
 ('CATHEDRAL PKWY', 'Cathedral Pkwy'),
 ('FORDHAM RD', 'Fordham Rd'),
 ('INWOOD-207 ST', 'Inwood - 207 St'),
 ('8 ST-NYU', '8 St - NYU'),
 ('CASTLE HILL AV', 'Castle Hill Av'),
 ('51 ST', '51 St'),
 ('SPRING ST', 'Spring St'),
 ('18 AV', '18 Av'),
 ('50 ST', 'Bay 50 St'),
 ('190 ST', '190 St'),
 ('BAY RIDGE AV', 'Bay Ridge - 95 St'),
 ('28 ST', '28 St'),
 ('21 ST-QNSBRIDGE', '21 St - Queensbridge'),
 ('39 AV', '39 Av'),
 ('TWENTY THIRD ST', nan),
 ('BAYCHESTER AV', 'Baychester Av'),
 ('BEVERLEY ROAD', 'Beverley Rd'),
 ('207 ST', '207 St'),
 ('AVENUE U', 'Avenue U'),
 ('VAN SICLEN AV', 'Van Siclen Av'),
 ('JACKSON AV', 'Jackson Av'),
 ('E 149 ST', 'E 149 St'),
 ('36 ST', 'Beach 36 St'),
 ('TOMPKINSVILLE', 'Tompkinsville'),
 ('W 8 ST-AQUARIUM', 'W 8 St - NY Aquarium'),
 ('175 ST', '175 St'),
 ('169 ST', '169 St'),
 ('WORLD TRADE CTR', 'World Trade Center'),
 ('20 AV', '20 Av'),
 ('PARKSIDE AV', 'Parkside Av'),
 ('BEDFORD PK BLVD', 'Bedford Park Blvd'),
 ('AVENUE J', 'Avenue J'),
 ('88 ST', '88 St'),
 ('ALLERTON AV', 'Allerton Av'),
 ('HOUSTON ST', 'Houston St'),
 ('MONTROSE AV', 'Montrose Av'),
 ('JAY ST-METROTEC', 'Jay St - MetroTech'),
 ('NEWARK HM HE', nan),
 ('SIMPSON ST', 'Simpson St'),
 ('191 ST', '191 St'),
 ('KINGSTON AV', 'Kingston Av'),
 ('CHAMBERS ST', 'Chambers St'),
 ('SHEPHERD AV', 'Shepherd Av'),
 ('14 ST', '14 St'),
 ('CONEY IS-STILLW', 'Coney Island - Stillwell Av'),
 ('ELDER AV', 'Elder Av'),
 ('NEVINS ST', 'Nevins St'),
 ('NEW UTRECHT AV', 'New Utrecht Av'),
 ('72 ST', '72 St'),
 ('138/GRAND CONC', '138 St - Grand Concourse'),
 ('FREEMAN ST', 'Freeman St'),
 ('ROCKAWAY AV', 'Rockaway Av'),
 ('45 ST', '45 St'),
 ('ZEREGA AV', 'Zerega Av'),
 ('CLEVELAND ST', 'Cleveland St'),
 ('BRONX PARK EAST', 'Bronx Park East'),
 ('GUN HILL RD', 'Gun Hill Rd'),
 ('METROPOLITAN AV', 'Middle Village - Metropolitan Av'),
 ('BAY 50 ST', 'Bay 50 St'),
 ('1 AV', '1 Av'),
 ('149/GRAND CONC', '149 St - Grand Concourse'),
 ('MYRTLE-WILLOUGH', 'Myrtle - Willoughby Avs'),
 ('RIT-ROOSEVELT', nan),
 ('THIRTY THIRD ST', nan),
 ('PATH WTC', nan),
 ('15 ST-PROSPECT', '15 St - Prospect Park'),
 ('75 AV', '75 Av'),
 ('163 ST-AMSTERDM', '163 St - Amsterdam Av'),
 ('MT EDEN AV', 'Mt Eden Av'),
 ('MIDDLETOWN RD', 'Middletown Rd'),
 ('ASTORIA DITMARS', 'Astoria - Ditmars Blvd'),
 ('AVENUE I', 'Avenue I'),
 ('RECTOR ST', 'Rector St'),
 ("E 143/ST MARY'S", "E 143 St - St Mary's St"),
 ('183 ST', '183 St'),
 ('LORIMER ST', 'Lorimer St'),
 ('BRIARWOOD', 'Briarwood - Van Wyck Blvd'),
 ('8 AV', '8 Av'),
 ('170 ST', '170 St'),
 ('80 ST', '80 St'),
 ('176 ST', '176 St'),
 ('181 ST', '181 St'),
 ('161/YANKEE STAD', '161 St - Yankee Stadium'),
 ('AVENUE X', 'Avenue X'),
 ('VAN SICLEN AVE', 'Van Siclen Av'),
 ('3 AV 138 ST', '3 Av - 138 St'),
 ('QUEENSBORO PLZ', nan),
 ('OZONE PK LEFFRT', 'Ozone Park - Lefferts Blvd'),
 ('231 ST', '231 St'),
 ('JEFFERSON ST', 'Jefferson St'),
 ('57 ST-7 AV', '57 St - 7 Av'),
 ('6 AV', '6 Av'),
 ('LIBERTY AV', 'Liberty Av'),
 ('157 ST', '157 St'),
 ('34 ST-PENN STA', '34 St - Penn Station'),
 ('HARLEM 148 ST', 'Harlem - 148 St'),
 ('CATHEDRAL PKWY', 'Cathedral Pkwy (110 St)'),
 ('BROADWAY', 'Broadway'),
 ('NEW LOTS AV', 'New Lots Av'),
 ('NEPTUNE AV', 'Neptune Av'),
 ('BEDFORD AV', 'Bedford Av'),
 ('AVENUE M', 'Avenue M'),
 ('145 ST', '145 St'),
 ('9TH STREET', nan),
 ('DEKALB AV', 'DeKalb Av'),
 ('CORTLANDT ST', 'Cortlandt St'),
 ('5 AVE', '5 Av'),
 ('NEWARK HW BMEBE', nan),
 ('MYRTLE AV', 'Myrtle Av'),
 ('DYCKMAN ST', 'Dyckman St'),
 ('4 AV-9 ST', '4 Av'),
 ('V.CORTLANDT PK', 'Van Cortlandt Park - 242 St'),
 ('ATL AV-BARCLAY', 'Atlantic Av - Barclays Ctr'),
 ('BEVERLY RD', 'Beverly Rd'),
 ('233 ST', '233 St'),
 ('PAVONIA/NEWPORT', nan),
 ('79 ST', '79 St'),
 ('GRAND ST', 'Grand St'),
 ('BERGEN ST', 'Bergen St'),
 ('96 ST', '96 St'),
 ('RALPH AV', 'Ralph Av'),
 ('9 AV', '9 Av'),
 ('BAY PKWY', 'Bay Pkwy'),
 ('BEACH 60 ST', 'Beach 60 St'),
 ('LIVONIA AV', 'Livonia Av'),
 ('BEACH 44 ST', 'Beach 44 St'),
 ('LONGWOOD AV', 'Longwood Av'),
 ('PARK PLACE', 'Park Pl'),
 ('FAR ROCKAWAY', 'Far Rockaway - Mott Av'),
 ('BROAD CHANNEL', 'Broad Channel'),
 ('PRESIDENT ST', 'President St'),
 ('GRANT AV', 'Grant Av'),
 ('63 DR-REGO PARK', '63 Dr - Rego Park'),
 ('COURT SQ', 'Court Sq'),
 ('110 ST', '110 St'),
 ('BUHRE AV', 'Buhre Av'),
 ('CLARK ST', 'Clark St'),
 ('NEWARK BM BW', nan),
 ('3 AV', '3 Av'),
 ('DELANCEY/ESSEX', 'Delancey St'),
 ('215 ST', '215 St'),
 ('SENECA AVE', 'Seneca Av'),
 ('E 180 ST', 'E 180 St'),
 ('GRD CNTRL-42 ST', 'Grand Central - 42 St'),
 ('LEXINGTON AV/53', 'Lexington Av/53 St'),
 ('219 ST', '219 St'),
 ('FLUSHING AV', 'Flushing Av'),
 ('ST. GEORGE', 'St George'),
 ('NORWOOD AV', 'Norwood Av'),
 ('PARK PLACE', 'Grand Central - 42 St'),
 ('71 ST', '71 St'),
 ('5 AV/59 ST', '5 Av/59 St'),
 ('90 ST-ELMHURST', '90 St - Elmhurst Av'),
 ('33 ST-RAWSON ST', '33 St'),
 ('BOROUGH HALL', 'Borough Hall'),
 ('CITY / BUS', nan),
 ('CLASSON AV', 'Classon Av'),
 ('ALABAMA AV', 'Alabama Av'),
 ('JUNCTION BLVD', 'Junction Blvd'),
 ('HUNTS POINT AV', 'Hunts Point Av'),
 ('NEWKIRK AV', 'Newkirk Av'),
 ('CENTRAL PK N110', 'Central Park North (110 St)'),
 ('36 ST', '36 St'),
 ('GROVE STREET', nan),
 ('OCEAN PKWY', 'Ocean Pkwy'),
 ('JFK JAMAICA CT1', nan),
 ('25 ST', '25 St'),
 ('MORISN AV/SNDVW', 'Morrison Av- Sound View'),
 ('PRINCE ST', 'Prince St'),
 ('CITY HALL', 'City Hall'),
 ('HALSEY ST', 'Halsey St'),
 ('238 ST', '238 St'),
 ('WEST FARMS SQ', 'West Farms Sq - E Tremont Av'),
 ('HUNTERS PT AV', 'Hunters Point Av'),
 ('INTERVALE AV', 'Intervale Av'),
 ('SMITH-9 ST', 'Smith - 9 Sts'),
 ('116 ST-COLUMBIA', '116 St - Columbia University'),
 ('NORWOOD 205 ST', 'Norwood - 205 St'),
 ('116 ST', '116 St'),
 ('JAMAICA CENTER', 'Jamaica Center - Parsons/Archer'),
 ('30 AV', '30 Av'),
 ('DITMAS AV', 'Ditmas Av'),
 ('174-175 STS', '174-175 Sts'),
 ('RIT-MANHATTAN', nan),
 ('BOWLING GREEN', 'Bowling Green'),
 ('TREMONT AV', 'Tremont Av'),
 ('STEINWAY ST', 'Steinway St'),
 ('BEACH 36 ST', 'Beach 36 St'),
 ('PATH WTC 2', nan),
 ('GREENPOINT AV', 'Greenpoint Av'),
 ('42 ST-PORT AUTH', '42 St - Port Authority Bus Terminal'),
 ('23 ST', '23 St'),
 ('135 ST', '135 St'),
 ('59 ST COLUMBUS', '59 St - Columbus Circle'),
 ('182-183 STS', '182-183 Sts'),
 ('WILSON AV', 'Wilson Av'),
 ('WOODHAVEN BLVD', 'Woodhaven Blvd'),
 ('52 ST', '52 St'),
 ('BAY RIDGE AV', 'Bay Ridge Av'),
 ('PROSPECT AV', 'Prospect Av'),
 ('42 ST-BRYANT PK', '42 St - Bryant Pk'),
 ('FRESH POND RD', 'Fresh Pond Rd'),
 ('NEWKIRK PLAZA', 'Newkirk Plaza'),
 ('NORTHERN BLVD', 'Northern Blvd'),
 ('DELANCEY/ESSEX', 'Essex St'),
 ('14 ST-UNION SQ', '14 St - Union Sq'),
 ('FOREST HILLS 71', 'Forest Hills - 71 Av'),
 ('CENTRAL AV', 'Central Av'),
 ('BOWERY', 'Bowery'),
 ('CANAL ST', 'Canal St'),
 ('FULTON ST', 'Fulton St'),
 ('PARSONS BLVD', 'Parsons Blvd'),
 ('50 ST', '50 St'),
 ('SARATOGA AV', 'Saratoga Av'),
 ('CORTELYOU RD', 'Cortelyou Rd'),
 ('MORRIS PARK', 'Morris Park'),
 ('AVENUE P', 'Avenue P'),
 ('KNICKERBOCKER', 'Knickerbocker Av'),
 ('SUTPHIN BLVD', 'Sutphin Blvd - Archer Av - JFK Airport'),
 ('SUTPHIN-ARCHER', 'Sutphin Blvd'),
 ('ASTORIA BLVD', 'Astoria Blvd'),
 ('75 ST-ELDERTS', '75 St'),
 ('ATLANTIC AV', 'Atlantic Av'),
 ('103 ST-CORONA', '103 St - Corona Plaza'),
 ('YORK ST', 'York St'),
 ('AQUEDUCT N.COND', 'Aqueduct - N Conduit Av'),
 ('ASTOR PL', 'Astor Pl'),
 ('CROWN HTS-UTICA', 'Crown Hts - Utica Av'),
 ('49 ST', '49 St'),
 ('FOREST AVE', 'Forest Av'),
 ('2 AV', '2 Av'),
 ('103 ST', '103 St'),
 ('BURKE AV', 'Burke Av'),
 ('W 4 ST-WASH SQ', nan),
 ('WHITEHALL S-FRY', 'Whitehall St'),
 ('MYRTLE-WYCKOFF', 'Myrtle - Wyckoff Avs'),
 ('BAY RIDGE-95 ST', 'Bay Ridge - 95 St'),
 ('METS-WILLETS PT', 'Mets - Willets Point'),
 ('174 ST', '174 St'),
 ('NEW LOTS', 'New Lots Av'),
 ('ROCKAWAY PARK B', 'Rockaway Park - Beach 116 St'),
 ('82 ST-JACKSON H', '82 St - Jackson Hts'),
 ('BROOKLYN BRIDGE', 'Brooklyn Bridge - City Hall'),
 ('ROCKAWAY BLVD', 'Rockaway Blvd'),
 ('EXCHANGE PLACE', nan),
 ('GATES AV', 'Gates Av'),
 ('MOSHOLU PKWY', 'Mosholu Pkwy'),
 ('111 ST', '111 St'),
 ('BOTANIC GARDEN', 'Botanic Garden'),
 ('BLEECKER ST', 'Bleecker St'),
 ('HIGH ST', 'High St'),
 ('KOSCIUSZKO ST', 'Kosciuszko St'),
 ('PARKCHESTER', 'Parkchester'),
 ('25 AV', '25 Av'),
 ('HARRISON', nan),
 ('BROOK AV', 'Brook Av'),
 ('121 ST', '121 St'),
 ('UNION ST', 'Union St'),
 ('69 ST', '69 St'),
 ('PELHAM PKWY', 'Pelham Pkwy'),
 ('AVENUE H', 'Avenue H'),
 ('CARROLL ST', 'Carroll St'),
 ('AQUEDUCT RACETR', 'Aqueduct - N Conduit Av'),
 ('METROPOLITAN AV', 'Metropolitan Av'),
 ('MARCY AV', 'Marcy Av'),
 ('21 ST', '21 St'),
 ('WOODLAWN', 'Woodlawn'),
 ('104 ST', '104 St'),
 ('14TH STREET', '14 St')}

In [20]:
nans = [pair for pair in diff_stations if np.nan in pair]
print('{} Stations do not have location information: {} of total'.format(len(nans), len(nans)/len(diff_stations)))

362630 Stations do not have location information: 0.06985371807360694 of total

## Pickle the turnstile data with lat/longs

In [36]:
turns_loc.to_pickle('data/turns_data_locations.pkl')